module.exports = function (grunt) {
    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        less:{
            development:{
                files:{
                    './dev/styles/main.css':'./src/styles/main.less'
                }
            },
            production:{
                options:{
                    compress:true,
                },
                files:{
                    './dist/styles/main.min.css':'./src/styles/main.less'
                }
            }
        },
        replace:{
            dev:{
                options:{
                    patterns:[
                        {
                            match:'ENDERECO_DO_CSS',
                            replacement: './styles/main.css'
                        },
                        {
                            match:'ENDERECO_DO_JS',
                            replacement:'./scripts/main.js'
                        }
                    ]
                },
                files:[
                    {
                        expand:true,
                        flatten:true,
                        src:'src/index.html',
                        dest:'dev/'
                    },
                    {
                        src:'src/script/main.js',
                        dest:'dev/scripts/'
                    }
                ]
            },
            dist:{
                options:{
                    patterns:[
                        {
                            match:'ENDERECO_DO_CSS',
                            replacement: './styles/main.min.css'
                        },
                        {
                            match:'ENDERECO_DO_JS',
                            replacement:'./scripts/main.min.js'
                        }
                    ]
                },
                files:[
                    {
                        expand:true,
                        flatten:true,
                        src:'prebuild/index.html',
                        dest:'dist/'
                    }
                ]
            }
        },
        watch:{
            less:{
                files:['src/styles/main.less'],
                target:['less:development']
            },
            html:{
                files:['src/index.html'],
                target:['replace:dev']
            },
            js:{
                files:['src/scripts/main.js'],
                target:['replace:dev']
            }

        },
        htmlmin:{
            dist:{
                options:{
                    removeComments:true,
                    collapseWhitespace:true,
                },
                files:{
                    'prebuild/index.html':'src/index.html'
                }
            }
        },
        uglify:{
            target:{
                files:{
                    'dist/scripts/main.min.js':'src/scripts/main.js'
                }
            }
        },
        clean:['prebuild']
    })

    grunt.loadNpmTasks('grunt-contrib-less')
    grunt.loadNpmTasks('grunt-contrib-watch')
    grunt.loadNpmTasks('grunt-contrib-htmlmin')
    grunt.loadNpmTasks('grunt-replace')
    grunt.loadNpmTasks('grunt-contrib-clean')
    grunt.loadNpmTasks('grunt-contrib-uglify')

    grunt.registerTask('default',['watch'])
    grunt.registerTask('build',['less:production','htmlmin:dist','replace:dist','uglify:target','clean'])
    grunt.registerTask('less1','less:production')
    grunt.registerTask('js','uglify:target')
}